name:                exception-handling
version:             0.1.0.0
github:              "subhodi/haskell-exception-handling"
license:             BSD3
author:              "Subhod I"
maintainer:          "subhodpoojary@gmail.com"
copyright:           "2019 Subhod I"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/subhodi/haskell-exception-handling#readme>

dependencies:
- base >= 4.7 && < 5
- mtl
- safe-exceptions
- text

library:
  source-dirs: src

executables:
  exception-handling-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - exception-handling

tests:
  exception-handling-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - exception-handling
